# Server
server.port=${PORT:8080}

# Database
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=America/Sao_Paulo

# GeckoAPI
geckoapi.base-url=${GECKOAPI_BASE_URL:https://api.geckoapi.com.br}
geckoapi.api-key=${GECKOAPI_API_KEY}

# Logging
logging.file.name=logs/fly-free.log
logging.level.br.com.flyfree=DEBUG
logging.level.org.springframework.web=DEBUG
